---
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub 'encryptedkmsbucket-${AWS::Region}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled

      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
            KMSMasterKeyID: "arn:aws:kms:ap-south-1:233402516001:key/f1043df7-03a9-45f8-897a-7c2d8285ae2d" 
    
    DeletionPolicy: Delete
Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket